### ISSUE TITLE
Bot Token

### ISSUE THREAD

**Issue by UnimatrixZeroOne** [jpbailey76/FF-Bot#1]
It appears you did not remove your bot token in the two or so files when pushing them here.

**Comment by jpbailey76** [comment]
Well that's a big mistake... Thanks for the heads up! You try using the bot at all?

**Comment by UnimatrixZeroOne** [comment]
I am going to try to get it up and running. Don't know python very well, so I have to see if I can understand it enough to set it up without instructions :P
